config/routes.rb
Rails.application.routes.draw do
  get 'report/make_report'
  get 'report/print_report'
  post 'report/post_report'
  resources :reports
  resources :notifications
  resources :messages
  resources :buys
  resources :products
  devise_for :clients
  devise_for :users
  resources :clients, only: [:index, :show]
  resources :users, only: [:show]
  get 'static_pages/home'
  get 'static_pages/benefits'
  get 'static_pages/trending'
  get 'static_pages/categories'
  get 'static_pages/sales'
  get 'static_pages/improvements'
  get 'static_pages/home'
  get 'static_pages/help'
  post 'static_pages/make_buy'
  root 'static_pages#home'
end

app/models/buy.rb
class Buy < ApplicationRecord
end

app/controllers/buys_controller.rb
class BuysController < ApplicationController
  before_action :set_buy, only: [:show, :edit, :update, :destroy]

  # GET /buys
  # GET /buys.json
  def index
    @buys = Buy.all
  end

  # GET /buys/1
  # GET /buys/1.json
  def show
  end

  # GET /buys/new
  def new
    @buy = Buy.new
  end

  # GET /buys/1/edit
  def edit
  end

  # POST /buys
  # POST /buys.json
  def create
    @buy = Buy.new(buy_params)

    respond_to do |format|
      if @buy.save
        format.html { redirect_to products_path, notice: 'Buy was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @buy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buys/1
  # PATCH/PUT /buys/1.json
  def update
    respond_to do |format|
      if @buy.update(buy_params)
        format.html { redirect_to @buy, notice: 'Buy was successfully updated.' }
        format.json { render :show, status: :ok, location: @buy }
      else
        format.html { render :edit }
        format.json { render json: @buy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buys/1
  # DELETE /buys/1.json
  def destroy
    @buy.destroy
    respond_to do |format|
      format.html { redirect_to buys_url, notice: 'Buy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_buy
      @buy = Buy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def buy_params
      params.permit(:client_id, :product_id, :quantity, :ticket)
    end
end

app/helpers/buys_helper.rb
module BuysHelper
end

app/views/buys/_form.html.erb
<%= form_with(model: buy, local: true) do |form| %>
  <% if buy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(buy.errors.count, "error") %> prohibited this buy from being saved:</h2>

      <ul>
      <% buy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :client_id %>
    <%= form.number_field :client_id %>
  </div>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.number_field :product_id %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/buys/edit.html.erb
<h1>Editing Buy</h1>

<%= render 'form', buy: @buy %>

<%= link_to 'Show', @buy %> |
<%= link_to 'Back', buys_path %>

app/views/buys/index.html.erb
<div class="container-fluid">
  <h3 class="text-center py-2 my-3 mono-base">Carro de compras</h3>
  <div class="row text-center my-3">
    <div class="col-md-3">
      <h4>Productos</h4>
    </div>
    <div class="col-md-3">
      <h4>Precios</h4>
    </div>
    <div class="col-md-3">
      <h4>Descripción</h4>
    </div>
    <div class="col-md-3">
    </div>
  </div>
  <% total = 0 %>
  <% buy_client = Buy.where(client_id: current_client.id, ticket: current_client.compras) %>
  <% if buy_client.length > 0 %>
  <% buy_client.each do |element| %>
  <% product = Product.find(element.product_id) %>
  <div class="row text-center mb-3">
    <div class="col-md-3">
      <p><%= product.title %></p>
    </div>
    <div class="col-md-3">
      <p><%= product.price.to_s[0..-3] %></p>
    </div>
    <div class="col-md-3">
      <p><%= product.description %></p>
    </div>
    <div class="col-md-3">
      <%= button_to "X",
      {:controller => "buys", :action => "destroy",
      :id => element.id},
      :method=>:delete,
      class: "btn btn-success" %>
    </div>
  </div>
  <% total = total + product.price %>
  <% end %>
  <div class="container d-flex justify-content-end px-5 mx-5 my-2">
    <h4>Total: <%= total.to_s[0..-3] %> mxn</h4>
  </div>
  <div class="container d-flex justify-content-end px-5 mx-5">
    <%= button_to "Comprar",  static_pages_make_buy_path, class:"btn mono-base text-white my-2" %>
  </div>
  <% else %>
  <div class="container-fluid d-flex justify-content-center">
    <h3 class="my-5">¡No hay productos aquí!</h3>
  </div>
  <% end %>
</div>
<!--
<p id="notice"><%= notice %></p>

<h1>Buys</h1>

<table>
  <thead>
    <tr>
      <th>Client</th>
      <th>Product</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buys.each do |buy| %>
      <tr>
        <td><%= buy.client_id %></td>
        <td><%= buy.product_id %></td>
        <td><%= buy.quantity %></td>
        <td><%= link_to 'Show', buy %></td>
        <td><%= link_to 'Edit', edit_buy_path(buy) %></td>
        <td><%= link_to 'Destroy', buy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Buy', new_buy_path %>-->

app/views/buys/new.html.erb
<h1>New Buy</h1>

<%= render 'form', buy: @buy %>

<%= link_to 'Back', buys_path %>

app/views/buys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Client:</strong>
  <%= @buy.client_id %>
</p>

<p>
  <strong>Product:</strong>
  <%= @buy.product_id %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @buy.quantity %>
</p>

<%= link_to 'Edit', edit_buy_path(@buy) %> |
<%= link_to 'Back', buys_path %>