config/routes.rb
Rails.application.routes.draw do
  get 'report/make_report'
  get 'report/print_report'
  post 'report/post_report'
  resources :reports
  resources :notifications
  resources :messages
  resources :buys
  resources :products
  devise_for :clients
  devise_for :users
  resources :clients, only: [:index, :show]
  resources :users, only: [:show]
  get 'static_pages/home'
  get 'static_pages/benefits'
  get 'static_pages/trending'
  get 'static_pages/categories'
  get 'static_pages/sales'
  get 'static_pages/improvements'
  get 'static_pages/home'
  get 'static_pages/help'
  post 'static_pages/make_buy'
  root 'static_pages#home'
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.client_id = current_client.id

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      if user_signed_in?
        format.html { redirect_to user_path(current_user.id), notice: 'Producto eliminado con exito' }
        format.json { head :no_content }
      else
        format.html { redirect_to products_url, notice: 'Producto eliminado con exito' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :price, :description, :category, :stock, :width, :height, :depth, :client_id, :img)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :titulo %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :precio %>
    <%= form.number_field :price, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :descripción %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :categoría %>
    <%= form.select(:category, [[:tractor, 0], [:motocultor, 1], [:herramienta, 2]], {}, class: 'custom-select') %>
  </div>

  <div class="form-group">
    <%= form.label :stock %>
    <%= form.number_field :stock, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :anchura %>
    <%= form.number_field :width, class: 'form-control', step: :any %>
  </div>

  <div class="form-group">
    <%= form.label :altura %>
    <%= form.number_field :height, class: 'form-control', step: :any %>
  </div>

  <div class="form-group">
    <%= form.label :profundidad %>
    <%= form.number_field :depth, class: 'form-control', step: :any %>
  </div>

  <div class="form-group">
    <%= form.label :imagen %>
    <%= form.text_field :img, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<div class="container mt-5">
  <h1>Editing Product</h1>

  <%= render 'form', product: @product %>

  <%= link_to 'Show', @product %> |
  <%= link_to 'Back', products_path %>
</div>

app/views/products/index.html.erb
<div class="container mt-5">

<h1>Productos</h1>
<%= button_to 'New Product', new_product_path, method: :get, class: 'btn btn-lg btn-success' %>

  <div class="row mt-5">

    <% @products.each do |product| %>
      <div class="col-md-3">
        <div class="card text-white bg-success mb-5">
          <div class="card-header">
            <h4 class="card-title"><%= product.title %></h4>
            <h6><%= Client.find(product.client_id)["email"] %></h6>
          </div>
          <div class="card-body">
            <h6 class="card-text">Descripción: <%= product.description %></h6>
            <h6 class="card-text">Precio: <%= product.price %></h6>
            <%= image_tag(product.img, width: '100%') %>
          </div>
          <div class="card-footer">
            <%= button_to 'Mostrar', product_path(product.id), method: :get, class: 'btn btn-success' %>
            <% if product.client_id != current_client.id %>
            <%= button_to 'Agregar a carrito',
            {:controller => "buys", :action => "create", :client_id => current_client.id,
            :product_id => product.id,
            :quantity => 1,
            :ticket => current_client.compras},
            :method=>:post,
            class: "btn btn-success" %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

<br>

</div>

app/views/products/new.html.erb
<div class="container mt-5">
  <div class="card border-primary mb-3">
    <div class="card-header">Nuevo Producto</div>
    <div class="card-body">
      <%= render 'form', product: @product %>
      <%= link_to 'Back', products_path %>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<div class="container mt-5">
  <%= button_to 'Back', products_path, method: :get, class: 'btn btn-success mb-5' %>
  <div class="col card text-white bg-success mb-3">
    <div class="card-header">
      <%- if client_signed_in? %>
      <%- if @product.client_id == current_client.id %>
        <div class="btn-group" role="group" aria-label="Basic example">
          <%= button_to 'Edit', edit_product_path(@product), method: :get, class: 'btn btn-success' %>
          <%= button_to 'Delete', product_path(@product), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-success' %>
        </div>
      <%- else %>
      <% if @product.client_id != current_client.id %>
      <%= button_to 'Agregar a carrito',
      {:controller => "buys", :action => "create", :client_id => current_client.id,
      :product_id => @product.id,
      :quantity => 1,
      :ticket => current_client.compras},
      :method=>:post,
      class: "btn btn-success" %>
      <% end %>
      <%- end %>
      <%- end %>
      <%= button_to 'Reportar',
      {:controller => "reports", :action => "create", :client_id => @product.client_id,
      :product_id => @product.id},
      :method=>:post,
      class: "btn btn-success text-white" %>
    </div>
    <div class="card-body">
      <h4 class="card-title">
        <strong>Producto:</strong>
        <%= @product.title %>
      </h4>

      <p>
        <strong>Description:</strong>
        <%= @product.description %>
      </p>

      <p>
        <strong>Price:</strong>
        <%= @product.price %>
      </p>

      <p>
        <strong>Category:</strong>
        <%= @product.category %>
      </p>

      <p>
        <strong>Stock:</strong>
        <%= @product.stock %>
      </p>

      <p>
        <strong>Width:</strong>
        <%= @product.width %>
        <strong>Height:</strong>
        <%= @product.height %>
        <strong>Depth:</strong>
        <%= @product.depth %>
      </p>

      <p>
        <strong>Client:</strong>
        <%= Client.find(@product.client_id).email %>
      </p>

      <p>
        <strong>Img:</strong>
        <%= @product.img %>
      </p>
      <%= image_tag @product.img, class: 'img-fluid' %>

    </div>
  </div>
</div>