config/routes.rb
Rails.application.routes.draw do
  get 'report/make_report'
  get 'report/print_report'
  post 'report/post_report'
  resources :reports
  resources :notifications
  resources :messages
  resources :buys
  resources :products
  devise_for :clients
  devise_for :users
  resources :clients, only: [:index, :show]
  resources :users, only: [:show]
  get 'static_pages/home'
  get 'static_pages/benefits'
  get 'static_pages/trending'
  get 'static_pages/categories'
  get 'static_pages/sales'
  get 'static_pages/improvements'
  get 'static_pages/home'
  get 'static_pages/help'
  post 'static_pages/make_buy'
  root 'static_pages#home'
end

app/models/report.rb
class Report < ApplicationRecord
end

app/controllers/report_controller.rb
class ReportController < ApplicationController
  def post_report
    if params[:type] == 'print'
      redirect_to action: "print_report", ticket: params[:ticket]
    elsif params[:type] == 'make'
      redirect_to action: "make_report", ticket: params[:ticket]
    elsif params[:type] == 'send'
      ClientMailer.with(ticket: params[:ticket], client: current_client).send_ticket.deliver!
      redirect_to action: "make_report", ticket: params[:ticket]
    else
      redirect_to :back, alert: "Incorrecto"
    end
  end

  def make_report
    @buy_client = Buy.where(client_id: current_client.id, ticket: params[:ticket])
  end

  def print_report
    @buy_client = Buy.where(client_id: current_client.id, ticket: params[:ticket])
    render :layout => false
    response.headers['Content-Type'] = 'text/plain'
    response.headers['Content-Disposition'] = 'attachment; filename=ticket.txt'
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to root_path, notice: 'El reporte se ha enviado con exito' }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to user_path(current_user.id), notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.permit(:title, :body, :user_id, :product_id)
    end
end

app/helpers/report_helper.rb
module ReportHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= form_with(model: report, local: true) do |form| %>
  <% if report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.number_field :product_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1>Editing Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reports</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>User</th>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.title %></td>
        <td><%= report.body %></td>
        <td><%= report.user_id %></td>
        <td><%= report.product_id %></td>
        <td><%= link_to 'Show', report %></td>
        <td><%= link_to 'Edit', edit_report_path(report) %></td>
        <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Report', new_report_path %>

app/views/reports/new.html.erb
<div class="container-fluid d-flex justify-content-center">
  <div class="">
    <h1>New Report</h1>

    <%= render 'form', report: @report %>

    <%= link_to 'Back', reports_path %>
  </div>
</div>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @report.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @report.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @report.user_id %>
</p>

<p>
  <strong>Product:</strong>
  <%= @report.product_id %>
</p>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>